import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import { NoScriptAlert } from "@/components/NoScriptAlert";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* Google tag (gtag.js) — skipped on PR preview deployments.
            IS_PR_PREVIEW is injected at runtime by the deploy infra and read
            here server-side, so it must NOT be NEXT_PUBLIC_ (those inline at
            build time). */}
        {process.env.IS_PR_PREVIEW !== "true" && (
          <>
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-STVFHMQS05"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-STVFHMQS05');`}
            </Script>
          </>
        )}
      </head>
      <body className="min-h-full flex flex-col">
        <NoScriptAlert />
        {children}
      </body>
    </html>
  );
}
